---
name: Bundle-MetaSyntactic
version: 1.00
author:
  - "Philippe Bruhat (BooK), <book@cpan.org>"
abstract: All Acme::MetaSyntactic themes
license: perl
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Bundle::MetaSyntactic:
    file: lib/Bundle/MetaSyntactic.pm
    version: 1.00
resources:
  license: http://dev.perl.org/licenses/
