---
abstract: 'All Acme::MetaSyntactic themes'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-MetaSyntactic
provides:
  Bundle::MetaSyntactic:
    file: lib/Bundle/MetaSyntactic.pm
    version: 1.025
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/book/Bundle-MetaSyntactic
version: 1.025
